### ISSUE TITLE
Discuss options for saving custom markdown

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#1]

**Comment by Hopding** [comment]
I think we should use the term "annotations" or "markup", rather than "markdown". When I hear/read "markdown", I tend to confuse it with the [markup language](http://daringfireball.net/projects/markdown/).

**Comment by dane-johnson** [comment]
I agree, I think "Annotation" should be preferred vocab

**Comment by Hopding** [comment]
I think it would make sense to save the annotation in the code snippet's AST itself, be that inside the token nodes, or as a separate branch rooted at the top level of the tree. 

We can then just save the AST as JSON in a database, and retrieve it when a client visits the app with the snippet's ID in the URL. E.g. I could save a snippet of annotated code, and be given a URL like this: `codesplain.io/app/[id]`. This way a user can easily get back to their snippet, and also share it with others. It would also be handy to have a login (maybe with GitHub?) so users could access all of their saved snippets without having to generate a shareable URL.

Doing things this way would be very similar to skilldirectory in how we handle the data. Would we want any kind of a REST API, or would we just hook the UI into the database directly?

**Comment by thebho** [comment]
Closing
