### ISSUE TITLE
When saving annotation on a "saved" code snippet, that should also update the snippet in Redis automatically

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#102]

**Comment by dane-johnson** [comment]
Related to #73
Likely solveable by adding a GET endpoint to server

**Comment by thebho** [comment]
We could also do a background save state every 30s/1min

**Comment by solkaz** [comment]
Can we not just call the save function when we save an annotation?

**Comment by thebho** [comment]
That will create a new saved snippet

**Comment by solkaz** [comment]
If the user hasn't saved the snippet yet, should it create a new snippet ID in Redis?

**Comment by thebho** [comment]
I think this would only occur if the snippet has been previously saved
