### ISSUE TITLE
Disable the animation on language selector until we actually have another language to select

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#103]
Clicking on the triangle should do nothing.

**Comment by solkaz** [comment]
There isn't a prop to set that in Material-UI. However, looking into the `<SelectField />` component, it seems that it's just a wrapper around some other components (such as MenuItem and IconButton), so either we could hand-roll our own Select component, or possibly make our own fork of Material-UI to make modifications to

**Comment by solkaz** [comment]
I made an issue for the repo, and apparently it is a bug; I'm currently working on a fix for it in the Material-UI repo. So this isn't something that's dependent on our code, it's in Material-UI

**Comment by solkaz** [comment]
Once [this PR](https://github.com/callemall/material-ui/pull/6286) is merged, we can close this issue

**Comment by solkaz** [comment]
PR has been merged; closing this
