### ISSUE TITLE
Moving dev dependencies out of normal dependencies

### ISSUE THREAD

**Issue by solkaz** [maryvilledev/codesplainUI#126]
There are a few dependencies that can be moved to the `devDependencies` section, such as

- enzyme
- morgan (?)
- react-addons-test-utils
- react-test-renderer

Doing so would help us with our build times.

**Comment by dane-johnson** [comment]
Morgan would require some modification of the source, but the others I think can go

**Comment by solkaz** [comment]
This is blocked until we can remove the server, since we can't remove its dependencies right now.
