### ISSUE TITLE
Project Wikis

### ISSUE THREAD

**Issue by solkaz** [maryvilledev/codesplainUI#127]
It would be beneficial to edit our repo's wikis so we can have a centralized base of relevant information

**Comment by Hopding** [comment]
@solkaz This story seems general enough that it might not ever be closed. I certainly agree with making better use of our wikis, though. And I think that we have been doing that this sprint: https://github.com/maryvilledev/codesplain-lambdas/wiki, https://github.com/maryvilledev/codesplainUI/wiki. So I would like to close this story. If there is anything remaining that could use documenting, then it would be good to make specific stories for those items.

**Comment by Hopding** [comment]
@dane-johnson Please disregard my previous comment if you are planning on beefing up the wikis to close this story. Waffle didn't display you as the assignee until after I left that comment :)
