### ISSUE TITLE
Plan out embedding into Runestone

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#132]

**Comment by dane-johnson** [comment]
Should this be a spike?

**Comment by Hopding** [comment]
Yeah, it seems like something we should all discuss with a whiteboard handy.

**Comment by dane-johnson** [comment]
1. Create a stripped down version of the app that can be consumed from a CDN as script/stylesheet tags (Can use React for this).
2. Create Sphinx Extension that compiles to a format recognizable by this tag. (Stripped application will be a submodule of this)
3. Publish the extension to PyPI
4. Fork LaunchCode’s book and add the dependency
5. PR changes back to LC

**Comment by dane-johnson** [comment]
:point_up: Path to success

**Comment by dane-johnson** [comment]
Helpful links:
- http://www.sphinx-doc.org/en/stable/extdev/index.html#dev-extensions
- https://github.com/RunestoneInteractive/RunestoneComponents (All written as Sphinx extensions)
- https://github.com/RunestoneInteractive/RunestoneComponents/blob/master/README.rst#notes-for-more-advanced-users (How we can add the extension to Runestone)

**Comment by thebho** [comment]
I think the planning is Done
