### ISSUE TITLE
Fix the small window size spacing between token filters and their check boxes

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#135]
Shrinking the window size should not cause the token name text to smash into and over the check box

**Comment by Hopding** [comment]
I attempted to fix this today, but was unable to do so. The Material UI library we are using looks wonderful, and works properly for most use cases. But it doesn't seem to handle manual tweaking of its CSS to handle quirky edge cases like this very well. 

Somebody else may be able to fix this problem. If not, I suggest we use our own check boxes and styling (maybe borrow some of Material UIs, but not use their components directly). Or else figure out a different layout that will let us work around this problem.
