### ISSUE TITLE
Add Visual Notification for Parser Errors

### ISSUE THREAD

**Issue by Hopding** [maryvilledev/codesplainUI#143]
Right now all errors are being logged to the console. We should instead handle errors by displaying a red squiggly, like most IDEs, in the Snippet editor itself.

**Comment by solkaz** [comment]
Right now the parser spits out a generic `SyntaxError` if it cannot parse the snippet; I think this is blocked until the parser can return relevant information, like where it failed, etc.

**Comment by thebho** [comment]
Can use start and end character of error
