### ISSUE TITLE
Restore Snippet Highlighting When Filters Are  Changed

### ISSUE THREAD

**Issue by Hopding** [maryvilledev/codesplainUI#174]
A regression has occurred during the redux branch merge, which removed the immediate triggering of a snippet re-highlight when the state of the filters changes. The result is a noticeable delay in the re-highlighting of a snippet in response to a filter toggle, because the highlighting is only performed by the parser "daemon" every second.

A potential fix for this would be to subscribe to changes in the state of the filters in the redux store, and trigger a re-highlight when it is updated.

**Comment by dane-johnson** [comment]
Possible solution is to dispatch an action to Redux that will trigger a highlight.
