### ISSUE TITLE
Limit Github Auth to only members of Maryville DevCenter or https://github.com/LaunchCodeEducation organizations

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#188]

**Comment by dane-johnson** [comment]
@thebho Should this be part of the Authorizer or should we not allow people who aren't members of the orgs to log in in the first place?

**Comment by thebho** [comment]
I think that is fair, block it on /auth and not in the validation function

**Comment by dane-johnson** [comment]
Do we need to do both? Is it possible to get a token without authenticating, say by using a personal access token?

**Comment by thebho** [comment]
If we use this pattern: https://developer.github.com/v3/oauth_authorizations/#check-an-authorization
You would check the token off of our clientID, so a token that was created by a different authorization would fail
