### ISSUE TITLE
Add Support For Parser Tagging

### ISSUE THREAD

**Issue by Hopding** [maryvilledev/codesplainUI#206]
The parser now supports tagging functionality, which allows us to add tags to nodes that match certain patterns. This allows us to add more specific labels to certain tokens, such as `for_range` loops, rather than just `for_loop`. Or `function_call`, rather than just `expr`. We should add support for nodes that have these tags in the UI.

**Comment by dane-johnson** [comment]
@Hopding Where can I get a complete listing of new tags.

**Comment by dane-johnson** [comment]
@JWalker1995 Any idea where I can get information about this story?

**Comment by dane-johnson** [comment]
This issue is too vague, I am going to close it. All the work I've done can be found here.
https://github.com/maryvilledev/codesplainUI/tree/issue206
