### ISSUE TITLE
Highlighting not occuring when returning to a page.

### ISSUE THREAD

**Issue by dane-johnson** [maryvilledev/codesplainUI#220]
Upon returning to a previously filtered and annotated snippet, the UI doesn't immediately highlight.

**Comment by dane-johnson** [comment]
Likely a Codemirror issue, since returning to the page **does** propagate the new state down, and `componentDidUpdate` is being called in `src/components/Editor.jsx`

**Comment by solkaz** [comment]
Blocked on this as there is no way to save/return to a snippet in dev.

**Comment by dane-johnson** [comment]
Sandbox environment now in place, removing the block.
