### ISSUE TITLE
Implement Debug/Info logging to the console

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#223]
Prod users should not see parser errors

**Comment by dane-johnson** [comment]
Parser errors should be shown in all environments, just not printed to the console. We need to find a way to alert users to errors in their code.

**Comment by dane-johnson** [comment]
I suggest a red squiggly and hover text, so as not to be too invasive.

**Comment by dane-johnson** [comment]
Although, all the logging like below should be hidden
```
Object { language: "Python3", entry_rule: "file_input", rules: Object, symbol_name_map: Array[97] }  a77c0727ccd67e0b6979.worker.js:10:11302
thing Object { type: "trailed_atom", begin: 0, end: 4, tags: Array[0], children: Array[1] }  a77c0727ccd67e0b6979.worker.js:3:67
Cutoff in matcher 1 on node type "trailed_atom" at cond "root.children.length === 2"
```

**Comment by Hopding** [comment]
There is a separate story for the red squiggly visual: https://github.com/maryvilledev/codesplainUI/issues/143

**Comment by dane-johnson** [comment]
Doesn't seem to be an issue anymore. Closing.
