### ISSUE TITLE
Add a Pull Request template

### ISSUE THREAD

**Issue by solkaz** [maryvilledev/codesplainUI#235]
Make a Pull Request template for our projects to address the required acceptance criteria. It should include things such as "Adds relevant tests," issue it fixes, etc.

https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

**Comment by dane-johnson** [comment]
Does this issue also involve creating an issue template?

**Comment by solkaz** [comment]
🤔 that would be useful as well. But for now let's focus on the PR template, and we can create an issue... for the issue template

**Comment by dane-johnson** [comment]
Meta
