### ISSUE TITLE
Point the API variable in dev to: https://api.codesplain/dev and prod to: https://api.codesplain/api

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#256]
Probably do this during Circle based on master or tag build

**Comment by Hopding** [comment]
This seems to already be done in [`master`](https://github.com/maryvilledev/codesplainUI/blob/master/circle.yml). Though, the prod url is set to `api.codesplain.io/prod`, as opposed to `api.codesplain.io/api`. 

Sidenote: I think it would make the most sense to have the prod api be just `api.codesplain.io`, as `api.codesplain.io/prod` and `api.codesplain.io/api` both seem somewhat redundant.
