### ISSUE TITLE
Run the parser only if trimmed contents have changed

### ISSUE THREAD

**Issue by solkaz** [maryvilledev/codesplainUI#273]
The parser is being run any time the snippet's contents change, but I think that it's unnecessary to do so if a whitespace is appended/prepended because it shouldn't change the meaning of the program. Before we send a snippet to be parsed, then, we should trim the snippet's contents and compare it to the saved snippet in the state; if they differ, then it needs to be parsed, but otherwise we do nothing.

**Comment by thebho** [comment]
Keep a cache in case you change it back?
