### ISSUE TITLE
Research Redux

### ISSUE THREAD

**Issue by dane-johnson** [maryvilledev/codesplainUI#3]

**Comment by solkaz** [comment]
http://redux.js.org/

**Comment by solkaz** [comment]
https://egghead.io/courses/getting-started-with-redux

https://egghead.io/courses/building-react-applications-with-idiomatic-redux

**Comment by dane-johnson** [comment]
I like the Redux time-travel idea, maybe we could use it to store back states of the snippet.

**Comment by dane-johnson** [comment]
https://youtu.be/xsSnOQynTHs

**Comment by dane-johnson** [comment]
I think this should be a priority sprint 2.

**Comment by Hopding** [comment]
How exactly will our app benefit from redux? It's an interesting, new (at least to me) tool. But keeping in mind what is mentioned [here](https://medium.com/@dan_abramov/you-might-not-need-redux-be46360cf367#.84oyentog)), why should we use it?

**Comment by thebho** [comment]
Let's discuss this tomorrow.  We can make this an Epic/Label and start to add stories for implementing Redux
