### ISSUE TITLE
Support multiple languages in the language selector

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#310]
- Python3, Java
- Pull new parser when you chose the language
- Confirm that the parsers are being cached

**Comment by dane-johnson** [comment]
This will involve changing some hard-coded values, and standardizing the name the environment variable is exported under in [Codesplain](https://github.com/maryvilledev/codesplain)

**Comment by Hopding** [comment]
@dane-johnson What environment variable are you referring to?

**Comment by dane-johnson** [comment]
Awaiting #341 to avoid conflicts.
