### ISSUE TITLE
Figure out how to handle Rules mapping for a new language

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#311]
Do we add another layer to the map or pull in a new rules file based on language

**Comment by dane-johnson** [comment]
I think that is wise. I believe the best implementation is to have the rules delivered to the application similarly to the parser. A CSV file makes sense to me given our current implementation.

**Comment by dane-johnson** [comment]
BTW I think this issue would be an excellent opportunity for **pair-programming**.
