### ISSUE TITLE
Refactor project to use React-Router v4 and idiomatic React-Router

### ISSUE THREAD

**Issue by solkaz** [maryvilledev/codesplainUI#342]
## Expected Behavior
- We would use React-Router v4
- There should be one way to redirect users

## Current Behavior
- We are using React-Router v3
- We have like a million different ways we redirect a user, like `window.location = ...` or `history.push()`

**Comment by dane-johnson** [comment]
We have two ways of redirecting, which you've enumerated. Maybe they can be clarified, but  we don't need a new tool to do that. The routing is completed for the project with no known bugs. Migrating will take time away from features we have prioritized.

**Comment by solkaz** [comment]
It isn't a new tool, and migration may take a day, if that. Sure, what we have is "good enough," but both methods we use are hacky code and aren't idiomatic; we'd want to use the [`withRouter`](https://github.com/ReactTraining/react-router/blob/v3/docs/API.md#withroutercomponent-options) HOC to provide access to the history object, not to directly access the `history` module

**Comment by dane-johnson** [comment]
It's not just good enough, it is complete. There is no new feature we need that it cannot provide, and there is no reason to use any time to port it over. If bugs are discovered, or new features need to be implemented, we should go for it, but as of right now this brings nothing to the project.

**Comment by solkaz** [comment]
Actually, there are. [`<Prompt />`](https://reacttraining.com/react-router/core/api/Prompt), so we can use a custom alert; there's [animated transitions](https://reacttraining.com/react-router/web/example/animated-transitions); and preventing transitions becomes much cleaner, all of which are impossible with v3. The code is more readable and maintainable, which has immediate value and reduces the chances of bugs, so there is value in upgrading. I'm not saying we need to upgrade now, I'm saying we *should* upgrade in the future, and likely sooner than later.
