### ISSUE TITLE
Add an indicator when loading a snippet

### ISSUE THREAD

**Issue by dane-johnson** [maryvilledev/codesplainUI#345]
## Expected Behavior

When returning to an existing snippet, there should be some indication that the snippet exists and is being loaded.

## Current Behavior

There is no indication that loading is occurring. The application state simply freezes until the snippet suddenly pops into existence.

## Possible Solution

Start an animation when the user loads a snippet, and end it when the snippet state is loaded.

**Comment by thebho** [comment]
Linked to #333
