### ISSUE TITLE
Pre-saved snippets are not actually being updated

### ISSUE THREAD

**Issue by solkaz** [maryvilledev/codesplainUI#350]
## Expected Behavior
If you have already saved a snippet and click the "Save" button (not Save As), it will make a PUT request to update the snippet

## Current Behavior
It sends a POST request every time you click save. If you refresh the page, React-Router will have its history updated, so it can get the id and then properly do PUT requests, but this is before the user has done so

## Steps to Reproduce (for bugs)

1. Start with a new snippet
2. Enter a title and body
3. Click save
4. Click save again. If you look at your network tab in the developer tools, two POST requests will have been sent, when there should've been a POST and then a PUT

## Possible Solution
This is due to how we are handling browser changes because we are using `browserHistory` instead of using the `withRouter` HOC. When you push to `browserHistory`, the app's router isn't in sync so it won't be able to read the id of the snippet in `handleSave()`

The need for these changes was partially discussed in #342

**Comment by dane-johnson** [comment]
This must be a regression. In the past I was working on some CORS errors and distinctly remember seeing a PUT request.
