### ISSUE TITLE
Research Babel error about Python parser thrown when running `yarn build`

### ISSUE THREAD

**Issue by dane-johnson** [maryvilledev/codesplainUI#36]

**Comment by solkaz** [comment]
Error given:

```
[BABEL] Note: The code generator has deoptimised the styling of "/Users/jmh/Programming/codesplainUI/src/parsers/python3.js" as it exceeds the max of "500KB".
```

**Comment by solkaz** [comment]
I believe it's not an error, just a note that it's not optimizing (minifying?) the script since it's too big. @JWalker1995 anyway we can work to shrink it down?

**Comment by JWalker1995** [comment]
I'm planning on running them through an optimizer in a bit

**Comment by dane-johnson** [comment]
Something I came across
https://webpack.js.org/configuration/performance/

**Comment by Hopding** [comment]
I think @solkaz is right. It seems to just be a note, not an error or warning. Even if it is, I'm not sure that it matters since we will be moving the parser out of the web app in a sprint or two?

**Comment by solkaz** [comment]
Yeah, I think so @Hopding. I think we can close this, unless we can't?

**Comment by dane-johnson** [comment]
Since we minified the parser this warning doesn't appear anymore.
