### ISSUE TITLE
When a user saves(PUT) a snippet that didn't have a snippetLanguage set previously, but does now, the language does not save

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#364]
## Expected Behavior
If I add or change the language of a saved snippet, calling `Save` should add the snippetLanguage to the saved data

## Current Behavior
The save is successful, but when I reload that snippet the language isn't included in the GET

## Steps to Reproduce (for bugs)
1. Load a snippet saved before 4/6
2. Set the language to Python 3
3. `Save` the snippet
4. Reload the page to see the language field blank

**Comment by thebho** [comment]
From grooming, please confirm that this is working as intended

**Comment by Hopding** [comment]
Closing. I tested this and it no longer appears to be a problem. Snippets without a language field are assumed to be `python3`, and if they are re-saved, they will be given a `snippetLanguage` field.
