### ISSUE TITLE
Highlighting is not updating when saving over a snippet

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#370]
## Expected Behavior
When I save a snippet that was already saved, the current highlight state should be updated in S3

## Current Behavior
Highlighting is persisting from the original save

## Steps to Reproduce (for bugs)
1. Save a snippet
2. Change the highlighting and save (PUT) the snippet
3. Reload the page

**Comment by thebho** [comment]
And now the behavior is WAI.  So this is inconsistently not working

**Comment by Hopding** [comment]
I tested this in dev, and am not able to reproduce the behavior. Have you encountered the problem since posting this issue?

**Comment by thebho** [comment]
It's still working as intended in Dev

**Comment by Hopding** [comment]
Closing because cannot reproduce.

**Comment by thebho** [comment]
Not working in Dev again
