### ISSUE TITLE
Active Annotations aren't discarded when navigating away from a page

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#379]
## Expected Behavior
If I am editing or viewing an Annotation and I click the Codesplain home button, the annotations should be discarded 

## Current Behavior
The "edit-mode" or "view-mode" stays with the current annotation until I refresh the page

## Steps to Reproduce (for bugs)
1. Create a new snippet
2. Lock the snippet
3. Add an annotation, don't save
4. Click `Codesplain` to navigate home
5. `Discard` unsaved changes

This is happening in Dev, but WAI in Prod

**Comment by dane-johnson** [comment]
Likely related to upgrading react-router

**Comment by thebho** [comment]
In prod it ask `Are you sure you want to reload` and in dev it asks `discard unsaved changes`
When did we make that change?

**Comment by dane-johnson** [comment]
https://github.com/maryvilledev/codesplainUI/commit/748f5285ce31cfec1051be5eccaa4643dfa87554

**Comment by dane-johnson** [comment]
I think the difference is that before, clicking navigating home did a full redirect, now I think it just changes the app state without doing a server call.
