### ISSUE TITLE
Shrink the TokenSelector component

### ISSUE THREAD

**Issue by solkaz** [maryvilledev/codesplainUI#39]
It has too much real estate. Shrink it down/move it/whatever

**Comment by thebho** [comment]
Here's Amazon, doesn't need to be bigger than this
![screen shot 2017-02-24 at 3 16 21 pm](https://cloud.githubusercontent.com/assets/12362348/23321256/3e58e36c-faa4-11e6-9b9f-603affa3e7e9.png)

**Comment by dane-johnson** [comment]
Issue name is a mistake I assume? What should it be?
