### ISSUE TITLE
As a github user, I should be able to delete a snippet

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#413]
Options:
- Add a delete button under the Filters panel
- Add a trash can or `x` on the right side of each snippet on the `My Snippets` menu
- Add a `Edit snippets` option that opens a modal that allows users to select multiple snippets with `Delete Selected`, `Select All`, `Clear Selected` options

**Comment by jdmaryville** [comment]
Blocked by number #421
