### ISSUE TITLE
The Select All and Clear All buttons need to take up less space when the window is smaller

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#414]
The buttons need to be next to each other or moved over to the right edge of the Filters panel

## Current Behavior
<img width="909" alt="screen shot 2017-04-18 at 7 56 09 am" src="https://cloud.githubusercontent.com/assets/12362348/25132163/203d7eb8-240e-11e7-8eb6-3fbc37d4ec35.png">

**Comment by Hopding** [comment]
Will be fixed in https://github.com/maryvilledev/codesplainUI/issues/278.
