### ISSUE TITLE
Long titles need padding between the language selector

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#415]
## Current Behavior
<img width="511" alt="screen shot 2017-04-18 at 8 16 14 am" src="https://cloud.githubusercontent.com/assets/12362348/25132514/7184d6a8-240f-11e7-8a50-1f16f350a301.png">

**Comment by Hopding** [comment]
Will be fixed in https://github.com/maryvilledev/codesplainUI/issues/278.
