### ISSUE TITLE
Fix contact area spillover

### ISSUE THREAD

**Issue by dane-johnson** [maryvilledev/codesplainUI#429]
## Expected Behavior

The contact info should remain distinct from the other components.
## Current Behavior

Contact info is appearing atop the other components.
![image_uploaded_from_ios_480](https://cloud.githubusercontent.com/assets/10768827/25397042/8388c52e-29ac-11e7-909f-df546764a231.jpg)

## Steps to Reproduce (for bugs)

1. Resize the window

## Possible Solution

N/A

**Comment by Hopding** [comment]
I am not sure if this is a problem, since we are not concerned about mobile support. That said, I would prefer to have the contact info in a footer, and doing so would fix this.

**Comment by Hopding** [comment]
Will be fixed by #462
