### ISSUE TITLE
Relocate next/prev buttons

### ISSUE THREAD

**Issue by Hopding** [maryvilledev/codesplainUI#432]
## Expected Behavior

It should be possible to move through the next/prev annotations in a snippet, regardless of an annotation's length, without having to move my cursor up/down.

## Current Behavior

If I am viewing annotations of different lengths, then the buttons will shift up and down depending on the annotation's size, thereby forcing me to move my cursor to use the next/prev buttons.

## Screenshots
Notice the differing locations of the next/prev buttons in the screenshots below:

### Annotation with shorter height
![screen shot 2017-04-25 at 3 59 15 pm](https://cloud.githubusercontent.com/assets/10351828/25407531/39b3cbaa-29d0-11e7-88e1-8fddc38cc6b7.png)

### Annotation with greater height
![screen shot 2017-04-25 at 3 59 30 pm](https://cloud.githubusercontent.com/assets/10351828/25407530/39b2d862-29d0-11e7-94be-25c12cfd3c82.png)

**Comment by dane-johnson** [comment]
Possible solution, move to top.
