### ISSUE TITLE
Stop abusing react-cookies

### ISSUE THREAD

**Issue by solkaz** [maryvilledev/codesplainUI#443]
React-cookies is fine, and we use it for valid reasons, such as saving a user's token. However, I'm starting to notice that it's being used in instances where it's unnecessary and possibly harmful, such as where we are loading a token from cookies when we have it stored in state. We have Redux for a reason, and that is to manage application state; cookies are only for cross-session data, such as tokens or usernames

**Comment by dane-johnson** [comment]
The most harmful thing you can possibly be storing is the token, it's the single point of entry for Codesplain and Github. What other data are being stored there?

**Comment by solkaz** [comment]
Username, organizations, user avatars.
