### ISSUE TITLE
Routing to url adjusted snippets isn't working in dev

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#451]
https%3A%2F%2Fgithub.com%2Ftest used to load my `https://github.com/test` snippet, now it is a Resource Not Found when using Safari

**Comment by thebho** [comment]
Updated: Works in Chrome, but not safari

**Comment by Hopding** [comment]
I can confirm. Works in Chrome, does not work in Firefox or Safari.

This is the first time something works in Chrome that doesn't in Firefox. Not the other way around :P
