### ISSUE TITLE
Text entry is being reversed

### ISSUE THREAD

**Issue by Hopding** [maryvilledev/codesplainUI#474]
## Expected Behavior

Text entry should _not_ be reversed.

## Current Behavior

Text entry _is_ being reversed. E.g. if I type `print('test')` into CodeMirror, `)'tset'(tnirp` is displayed instead.

## Steps to Reproduce (for bugs)

1. Open the app.
2. Type `print('test')`
3. Observe the result.

![screen shot 2017-05-11 at 11 05 08 am](https://cloud.githubusercontent.com/assets/10351828/25959672/08bc498e-363a-11e7-912e-ba6317255cff.png)

**Comment by dane-johnson** [comment]
https://github.com/maryvilledev/codesplainUI/blame/1325871b5ea4e119ee95a811c3f0c895eb408283/src/components/Editor.jsx#L47 This line needs to be added back. I failed to comment it as such but it was a guard statement against this bug.
