### ISSUE TITLE
Remove the black fill from the footer

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#486]

**Comment by solkaz** [comment]
@thebho like this?
<img width="1437" alt="screen shot 2017-05-15 at 8 34 14 am" src="https://cloud.githubusercontent.com/assets/10211603/26059987/4efe2ffe-3949-11e7-8934-1a37776d83c4.png">

**Comment by thebho** [comment]
Yeah, i was actually just trying this to see if I could figure it out. #makebriancodeagain
