### ISSUE TITLE
404 page not working

### ISSUE THREAD

**Issue by jdmaryville** [maryvilledev/codesplainUI#488]
## Expected Behavior

When navigating to a non existent snippet, user should be redirected to a 404 page.
## Current Behavior

User is not redirected to a 404 page when navigating to a 404 page. Instead, a user is redirected to the homepage.
## Steps to Reproduce (for bugs)

1. Navigate to an existing snippet (url)
2. Enter a nonexistent snippet to the url
3. Notice you are redirected to the homepage, not the error page.

**Comment by thebho** [comment]
Works in Chrome

**Comment by thebho** [comment]
And safari

**Comment by thebho** [comment]
Is anyone still having this issue?
