### ISSUE TITLE
Holding a character key does not repeat presses

### ISSUE THREAD

**Issue by dane-johnson** [maryvilledev/codesplainUI#493]
## Expected Behavior

Holding a character key should repeat character associated with the key.
## Current Behavior

Holding a key warms the CPU and not much else.
## Steps to Reproduce (for bugs)

1. Focus on the editor
2. Hold a character key

## Possible Solution

Look at the pushToCodeMirror guard statement.

**Comment by thebho** [comment]
Works in safari and chrome

**Comment by thebho** [comment]
Closing, this is a client setting problem
