### ISSUE TITLE
Snippet menu should open on click, not on hover

### ISSUE THREAD

**Issue by dane-johnson** [maryvilledev/codesplainUI#539]
## Expected Behavior

When I click the snippet menu, it should open

## Current Behavior

The menu opens when I hover on it. If I then click it, it *closes*. Very irritating.

## Browser

Firefox

## Steps to Reproduce (for bugs)

1. Hover over the snippet menu
2. Click it

**Comment by thebho** [comment]
I'm not sure I agree.  Other sites have menus that work like this

**Comment by dane-johnson** [comment]
Try it. It is actually annoying as all hell.

**Comment by thebho** [comment]
The fact that clicking on it closes it, is annoying.  I don't mind the hover behavior

**Comment by thebho** [comment]
This is a good example https://swgoh.gg

**Comment by thebho** [comment]
Also https://www.amazon.com.

Tabs (for navigating to another service/page) should be clickable
Menus (for expanding options) should trigger on a hover and go away when your mouse leaves the header/that menu

**Comment by dane-johnson** [comment]
These are both clickable because the header itself is an option. Clicking snippets isn't an option, so it shouldn't have an effect.

**Comment by thebho** [comment]
Yeah, i agree with that.  I'm saying Tabs and Menus are 2 different things, and this instance it's a menu, i.e. hover to open and move mouse away to close.  Clicking does nothing

**Comment by dane-johnson** [comment]
Fine with that, but clicking definitely shouldn't *close* the menu. That is the irritating part.
