### ISSUE TITLE
Syntax highlighting does not occur when returning to a page.

### ISSUE THREAD

**Issue by dane-johnson** [maryvilledev/codesplainUI#66]
If you create a snippet and save, then return to that page, the syntax highlighting will be gone.

Links to #85

**Comment by dane-johnson** [comment]
Possibly related to #69

**Comment by solkaz** [comment]
This is because we are triggering calls to highlight the snippet only when the `CodeMirror` component triggers the onChange event, and no where else, AFAIK.
