### ISSUE TITLE
Add Button to create a new snippet

### ISSUE THREAD

**Issue by dane-johnson** [maryvilledev/codesplainUI#68]
Creating a new snippet currently involves navigating back to the home screen manually in the browser bar. There should be a button that does this for the user.

**Comment by thebho** [comment]
I think we should link `Codeplain` title to a blank snippet.
Jeff and I have also discussed making the snippet editor have a menu bar which would have name, language, save, lock, and could have create new

**Comment by dane-johnson** [comment]
This could be accomplished by wrapping in a `<Link path="/"></Link>` tag
