### ISSUE TITLE
Lock state is not maintained when returning to a page.

### ISSUE THREAD

**Issue by dane-johnson** [maryvilledev/codesplainUI#69]
Simply reloading a page, or navigating away and back reverts the lock state.

**Comment by dane-johnson** [comment]
Possibly related to #66

**Comment by solkaz** [comment]
If we're loading from the URL (i.e. there was an ID param passed to AppBody), then we know that that snippet has been saved, and therefore should be readonly. Otherwise we've got a new snippet, and that needs to be unlocked
