### ISSUE TITLE
Info panel prompts to add an annotation before locked.

### ISSUE THREAD

**Issue by dane-johnson** [maryvilledev/codesplainUI#70]
The info panel has the text "Click on a line number to add an annotation or display one" before the view is locked, but this is misleading because you cannot add annotations before locking the code.

**Comment by solkaz** [comment]
We shouldn't be displaying the annotation panel anyways in edit mode, because you can't interact with it in any way. Only when you are in annotation mode should you be allowed to view it

**Comment by dane-johnson** [comment]
Agreed. Is this MVC?

**Comment by thebho** [comment]
No, but should be in v0.2
