### ISSUE TITLE
Add `+=` highlighting

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#75]

**Comment by thebho** [comment]
![screen shot 2017-03-01 at 3 47 41 pm](https://cloud.githubusercontent.com/assets/12362348/23483075/0302beae-fe97-11e6-8de3-9803b8ec6f6c.png)

**Comment by dane-johnson** [comment]
http://www.tutorialspoint.com/python/assignment_operators_example.htm
Might want to hit all of these
