### ISSUE TITLE
Importing snippet should include all state information

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#79]
Currently missing:
- [x] Lock state
- [x] Token Highlights Checked
- [ ] Previously Annotated lines

**Comment by solkaz** [comment]
If a snippet has been saved, then we can assume that it is locked, no?

**Comment by thebho** [comment]
Interesting question.  Probably, yes.  This is more about pulling up a saved snippet and having to re lock/highlight/etc...

**Comment by dane-johnson** [comment]
Presently this distinction is not made.

**Comment by dane-johnson** [comment]
Duplicate of #77

**Comment by thebho** [comment]
Added another feature that was missing from the Redis imports.

**Comment by dane-johnson** [comment]
Duplicate of #86

**Comment by thebho** [comment]
Fair enough, closing this
