### ISSUE TITLE
After pulling in a saved snippet, you should be able to change the highlighting filters

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#85]
Currently you can click on a checkbox, but the state of the checkbox and highlight does not change

**Comment by thebho** [comment]
![screen shot 2017-03-02 at 9 59 25 am](https://cloud.githubusercontent.com/assets/12362348/23515164/fe6f123c-ff2e-11e6-8103-e25b44deba63.png)

**Comment by Hopding** [comment]
This is fixed in https://github.com/maryvilledev/codesplainUI/pull/77.
