### ISSUE TITLE
Snackbar component does not notify the user about errors when saving

### ISSUE THREAD

**Issue by solkaz** [maryvilledev/codesplainUI#87]
When I clicked the save button, the snackbar message had said that it "saved". But opening the console told me that there was an error, and hadn't saved it.

Snackbar should be red

**Comment by dane-johnson** [comment]
What is the error message?

**Comment by Hopding** [comment]
Looking at the code, there is a `catch` func on the redis axios call, but it doesn't invoke the snackbar. It just logs the error. The snackbar is only invoked if it succeeds.

**Comment by solkaz** [comment]
It was a 404. I wasn't connected to Redis, yet it still said it saved
