### ISSUE TITLE
The 'locked' lock icon hover doesn't popup when directly over the

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#95]
![pasted image at 2017_03_02 11_03 am](https://cloud.githubusercontent.com/assets/12362348/23518307/ac9de0b4-ff38-11e6-8523-108e7c3ab1b1.png)

**Comment by fl0yd** [comment]
https://github.com/react-toolbox/react-toolbox/issues/651

**Comment by thebho** [comment]
@solkaz Do we need to just update the version of material-ui, or is this blocked until they have released that change?

**Comment by thebho** [comment]
Nevermind

**Comment by Hopding** [comment]
@thebho This does not seem to be an issue anymore in `master`. Can you please confirm this?

**Comment by Hopding** [comment]
It is still a problem, but does not occur in Firefox.

**Comment by Hopding** [comment]
Just wrapping the `<LockButton />` in a `div` and applying a tooltip to that fixes the problem. However, the styling is different from the Material UI tool tips. Does anybody care about this?

## Div Tooltips
![screen shot 2017-03-14 at 2 39 35 pm](https://cloud.githubusercontent.com/assets/10351828/23919286/50817314-08c4-11e7-9b18-9c71782c3da9.png)
![screen shot 2017-03-14 at 2 39 45 pm](https://cloud.githubusercontent.com/assets/10351828/23919285/507ca532-08c4-11e7-9ced-018945e5022a.png)

## Material UI Tooltip
![screen shot 2017-03-14 at 2 39 49 pm](https://cloud.githubusercontent.com/assets/10351828/23919287/50826d46-08c4-11e7-88d6-cae179509e05.png)
