### ISSUE TITLE
Language selector size should adjust with the column size

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#96]
![pasted image at 2017_03_02 10_40 am](https://cloud.githubusercontent.com/assets/12362348/23518385/dda456ca-ff38-11e6-8d1f-0f86beed826b.png)

**Comment by solkaz** [comment]
I believe this behavior originates from Material-UI,  so fixing this will involve fixing the SelectField component itself

**Comment by solkaz** [comment]
<img width="845" alt="screen shot 2017-03-13 at 9 28 14 am" src="https://cloud.githubusercontent.com/assets/10211603/23858771/92e07b7e-07cf-11e7-91b8-3c62ae5fee8a.png">

I believe that this is an issue with the TextField component's width. The underline element has a `width: 100%` property, so it relies on the TextField's width; TextField, however, has a fixed width, so our solution must give TextField a non-static width

**Comment by solkaz** [comment]
Moving to backlog since we've removed the component from master
