### ISSUE TITLE
Discuss annotation saving options

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#98]
Do we want to let anyone add/edit a snippet wiki style?
Do we want to restrict adding/editing to github authenticated users?
Do we want to restrict adding/editing to your own created snippets?
Do we want to let other users add additional snippets to a line/token, but not change another users?

**Comment by thebho** [comment]
Google Docs is a good example

**Comment by dane-johnson** [comment]
Is this a dead issue?
