### ISSUE TITLE
Fix CSS errors in console

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#99]
![pasted image at 2017_03_02 11_14 am](https://cloud.githubusercontent.com/assets/12362348/23518740/16dcf414-ff3a-11e6-9397-74477f97086a.png)

**Comment by solkaz** [comment]
Are these still occurring? I have not seen them anywhere.

**Comment by dane-johnson** [comment]
Seems like dead issue to me.

**Comment by dane-johnson** [comment]
Closing as Could Not Reproduce.
